# action.yml
name: 'Binary Signing'
description: 'Signs a binary using a certificate stored in S3'
inputs:
  pfx-file:
    description: 'certificate pfx file'
    required: true
  input-path:
    description: 'path for input binary to be signed'
    required: true
  output-path:
    description: 'path to output the signed binary'
    required: true
  cert-password:
    description: 'password for the certificate'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.pfx-file }}
    - ${{ inputs.input-path }}
    - ${{ inputs.output-path }}
    - ${{ inputs.cert-password }}
    - ${{ inputs.s3-output-path }}
